server:
  applicationConnectors:
    - type: http
      port: 9000

viewRendererConfiguration:
   .ftl:
      strict_syntax: yes
      whitespace_stripping: yes


template: Hello, %s!
defaultName: Stranger
